# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0beb549705d8fbda82583ad25c187020"
name = "pre-purchase-checkout-upsell"
handle = "pre-purchase-checkout-upsell-3"
application_url = "https://example.com/"
embedded = true

[build]
dev_store_url = "pete-brunton-s-functions-extensions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
